menu:
  é¦–é¡µ: /  #éœ€è¦hexo new page index,åœ¨index/index.mdå¡«å†™çš„å†…å®¹å°†ä¼šå±•ç°åœ¨é¦–é¡µä¸Š
  æ–‡ç« : /list/ # éœ€è¦hexo new page list
  # æ·»åŠ å…¶ä»–é¡µé¢æ ¼å¼ä¸¾ä¾‹ï¼š
  # å…³äº: /about/ # éœ€è¦hexo new page about
  # æ ‡ç­¾: /tags/ #éœ€è¦hexo new page tags
  # åˆ†ç±»: /categories/ # éœ€è¦hexo new page categories
  # ...

showInMenu:  # menu ä¸­çš„å“ªäº›é¡µé¢æ˜¾ç¤ºåœ¨é¦–é¡µä¸­ï¼ˆâ€œé¦–é¡µâ€å¿…å®šæ˜¾ç¤ºï¼‰
  - æ–‡ç«   # å°†åœ¨é¦–é¡µæ˜¾ç¤º æ–‡ç«  é“¾æ¥
  # - å…³äº
  # - æ ‡ç­¾
  # - åˆ†ç±»


index:  # é¦–é¡µçš„é¡µçœ‰é¡µè„š
  header: çœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜” 
  footer: Email:123456789@gmail.com # é™¤äº†å¯ä»¥å¡«å†™ä»»ä½•æ–‡å­—å¤–ï¼Œå¯ä»¥è‡ªåŠ¨é‚®ç®±é“¾æ¥åŒ–ï¼Œä½†éœ€æŒ‰ç…§è¿™ä¸ªæ ¼å¼å¡«å†™ï¼šEmail:xxx@gmail.com
  titlePosition: left # center | left  # é¦–é¡µæ ‡é¢˜çš„ä½ç½®

footerLink: # åº•éƒ¨çš„é“¾æ¥è‡ªå®šä¹‰
  info: Â© 1949-2023 China  # infoè¿™ä¸ªå•è¯ä¸èƒ½ä¿®æ”¹ï¼Œä¸æƒ³ä½¿ç”¨å¯ä¸ºç©º
  # æ·»åŠ é“¾æ¥æ ¼å¼ ä¸¾ä¾‹
  # å‹é“¾: /friends/ # éœ€è¦hexo new page friends
  # è”ç³»: /contact/ # éœ€è¦hexo new page contact
  # æ”¯æŒ: /support/ # éœ€è¦hexo new page support
  # ...

post: #é™¤é¦–é¡µä¹‹å¤–é¡µé¢
  footer: ğŸŒŠçœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”ğŸŒŠ   # åº•éƒ¨å·¦ä¾§ è‡ªå®šä¹‰ä¿¡æ¯
  themeInfo: true # true | false  # æ˜¯å¦å¼€å¯ åº•éƒ¨å³ä¾§ å£°æ˜æœ¬ç«™ä¿¡æ¯

# ç›¸å¯¹äºsourceç›®å½•ä¸‹çš„å¤´åƒurl
favicon: /img/favicon.webp

# ---------------------------------------------------------------------------------------
# ä»¥ä¸Šä¸ºåŸºæœ¬é…ç½®ï¼Œå®ç°äº†A4ä¸»é¢˜è¿½æ±‚çš„çº¯å‡€é£
# 
# ä»¥ä¸‹ä¸º éå¿…è¦ä¸å¿…æ›´æ”¹çš„é…ç½®
#
# psï¼šè¿˜æœ‰ç»è¿‡A4ä½œè€…æµ‹è¯•ï¼Œå¯ä¾›ä½ ä½¿ç”¨çš„æ’ä»¶ï¼Œè¯¦è§ï¼šhttps://ninojay.top/tags/hexoPlugin/
# ---------------------------------------------------------------------------------------

# ä½ å¯èƒ½ä¼šç”¨åˆ°çš„ https://ninojay.top/2023/website-cdn/
cdn:
  enable: true # å¦‚æœä½ ä¿®æ”¹äº† css/js ï¼Œä¹Ÿè®¸éœ€è¦æŠŠcdnè®¾ç½®ä¸ºfalseæ‰ä¼šç”Ÿæ•ˆ
  choose: jsdelivr  # aliyun | unpkg| jsdelivr  # éƒ½è°ƒæ•´ä¸ºåˆ©äºå›½å†…çš„cdnï¼Œå»ºè®®ä½¿ç”¨é»˜è®¤çš„ jsdelivr å³å¯

# å®éªŒæ€§åŠŸèƒ½ï¼šA4è‰²è°ƒè°ƒæ•´ï¼šé¢œè‰²æ­é…æ˜¯å¾ˆä¸»è§‚çš„è¡Œä¸º
# è®¾ç½®ä¸º false ä¸º A4 é»˜è®¤ç°ç™½è‰²è°ƒï¼Œå¯è®¾ç½®ä¸º true ç›´æ¥å¯åŠ¨ ä½“éªŒä¸‹ å¦ä¸€ç§ç»¿é‡‘é¢„ç½®è‰²è°ƒ
# æ³¨ï¼šé¢œè‰²ä»£ç éœ€åŠ â€œ#â€ï¼Œé¢œè‰²å•è¯ä¸éœ€è¦åŠ â€œ#â€
# æ›´å¤šA4è‰²è°ƒæ­é…æ¨èï¼šhttps://ninojay.top/hexoplugin/A4-color-change/
color: 
  enable: false # true | false 
  font: "#fec591" # å­—ä½“é¢œè‰²
  background: "#005454" # æœ€åº•éƒ¨å±‚èƒŒæ™¯é¢œè‰²
  indexBackGround: "#005454" # é¦–é¡µå±‚é¢œè‰²
  postBackGround: "#005454" # æ–‡ç« é¡µå±‚é¢œè‰²
  codeBackGround: "black" # ä»£ç å—èƒŒæ™¯é¢œè‰²
  codeFont: "white" # ä»£ç å—å­—ä½“é¢œè‰² 
  linkBeforeClick: "#fec591" # é“¾æ¥ç‚¹å‡»å‰çš„é¢œè‰²
  linkAfterClick: "#fec591" # é“¾æ¥ç‚¹å‡»åçš„é¢œè‰²

# ---------------------------------------------------------------------------------------
# Comment plugin
# è¯„è®ºæ’ä»¶ï¼šéœ€è¦æ ¹æ®æ•™ç¨‹è‡ªè¡Œéƒ¨ç½²è¯„è®ºæœåŠ¡
# ---------------------------------------------------------------------------------------
comment:
  enable: false 
  use: waline # values: waline

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:  # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html


version: v1.7.0
