menu:
  é¦–é¡µ: /
  æ–‡ç« : /list # éœ€è¦hexo new page list å¹¶ä¸”åœ¨å¯¹åº”é¡µé¢çš„ front-matteræ·»åŠ  layout: list
  å…³äº: /about # éœ€è¦hexo new page about


index:  # é¦–é¡µ
  header: çœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜” # é¦–é¡µçš„é¡µçœ‰
  footer: Email:123456789@gmail.com # é¦–é¡µçš„é¡µè„š

post:
  footer: ğŸŒŠçœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”ğŸŒŠ #é™¤é¦–é¡µä¹‹å¤–çš„é¡µé¢é¡µè„š


# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: false 
  use: waline # values: waline

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:   # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html

version: v1.1.3-dev