# å½“ä½ ç¬¬ä¸€æ¬¡ç©A4ï¼Œæƒ³ç›´æ¥çœ‹æ•ˆæœçš„è¯ï¼š
# 1. è¯·ç›´æ¥å»æ‰ menu é…ç½®ä¸­çš„  â€˜é¦–é¡µâ€™ å’Œ â€˜æ–‡ç« â€™ å‰çš„ â€˜#â€™ æ³¨é‡Šç¬¦å·
# 2. è¯·ç›´æ¥å»æ‰ showInMenu é…ç½®ä¸­çš„ â€˜- æ–‡ç« â€™ å‰çš„ â€˜#â€™ æ³¨é‡Šç¬¦å·
# 3. æ‰§è¡Œå‘½ä»¤ï¼šhexo new page index ç”Ÿæˆé¦–é¡µï¼›æ‰§è¡Œå‘½ä»¤ï¼šhexo new page list ç”Ÿæˆåˆ—è¡¨é¡µé¢ï¼›
# 4. æ‰§è¡Œå‘½ä»¤ï¼šhexo clean && hexo g && hexo s ç›´æ¥æŸ¥çœ‹é¡µé¢æ•ˆæœ
menu:
  # é¦–é¡µ: /  #éœ€è¦hexo new page index,åœ¨index/index.mdå¡«å†™çš„å†…å®¹å°†ä¼šå±•ç°åœ¨é¦–é¡µä¸Š
  # æ–‡ç« : /list/ # éœ€è¦hexo new page list
  # æ·»åŠ å…¶ä»–é¡µé¢æ ¼å¼ä¸¾ä¾‹ï¼š
  # å…³äº: /about/ # éœ€è¦hexo new page about
  # æ ‡ç­¾: /tags/ #éœ€è¦hexo new page tags
  # åˆ†ç±»: /categories/ # éœ€è¦hexo new page categories
  # ...

# é¦–é¡µä½ æƒ³è¦å±•ç¤ºçš„menué“¾æ¥ï¼Œæ³¨æ„å½“ä½ ä¿®æ”¹äº†menuä¸­çš„åˆ«åï¼Œè¿™é‡Œè¦éšç€æ›´æ”¹ï¼Œä¸ç„¶ä½ ä¼šç–‘æƒ‘æ€ä¹ˆé¦–é¡µæ²¡æœ‰ä¿®æ”¹åçš„åˆ«å
showInMenu:  # menu ä¸­çš„å“ªäº›é¡µé¢æ˜¾ç¤ºåœ¨é¦–é¡µä¸­ï¼ˆâ€œé¦–é¡µâ€å¿…å®šæ˜¾ç¤ºï¼‰
  # - æ–‡ç«   # å°†åœ¨é¦–é¡µæ˜¾ç¤º æ–‡ç«  é“¾æ¥
  # - å…³äº
  # - æ ‡ç­¾
  # - åˆ†ç±»

index:  # é¦–é¡µç›¸å…³é…ç½®
  header:  # é¦–é¡µçš„é¡µçœ‰ ä»¥åŠ 404é¡µé¢ï¼Œå½“ä½ æ²¡å¼€å¯ä¸€è¨€ï¼Œå°†ä¼šæ¯æ¬¡åˆ·æ–°é¡µé¢éšæœºå±•ç¤ºä¸‹é¢çš„è¯­å¥
    #- "æˆ‘å¿˜æ˜æœˆå¾ˆä¹…ï¼Œæ˜æœˆå§‹ç»ˆæœ›æˆ‘"
    #- "äººå±±äººæµ·ï¼Œäººæ¥äººå¾€"
    #- "çœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”"
    # ...
  hitokoto: false # ä¸€è¨€ï¼šè°ƒç”¨ç½‘ç»œè¯­å¥å±•ç¤ºçš„æ¥å£
  footer: Email:123456789@gmail.com # é™¤äº†å¯ä»¥å¡«å†™ä»»ä½•æ–‡å­—å¤–ï¼Œå¯ä»¥è‡ªåŠ¨é‚®ç®±é“¾æ¥åŒ–ï¼Œä½†éœ€æŒ‰ç…§è¿™ä¸ªæ ¼å¼å¡«å†™ï¼šEmail:xxx@gmail.com
  titlePosition: left # center | left  # é¦–é¡µæ ‡é¢˜çš„ä½ç½®
  width: small  # small | middle | big # é¦–é¡µçš„å®½åº¦

footerLink: # åº•éƒ¨çš„é“¾æ¥è‡ªå®šä¹‰
  info: Â© 1949-2024 China  # infoè¿™ä¸ªå•è¯ä¸èƒ½ä¿®æ”¹ï¼Œä¸æƒ³ä½¿ç”¨å¯ä¸ºç©º
  # æ·»åŠ é“¾æ¥æ ¼å¼ ä¸¾ä¾‹
  # å‹é“¾: /friends/ # éœ€è¦hexo new page friends
  # è”ç³»: /contact/ # éœ€è¦hexo new page contact
  # æ”¯æŒ: /support/ # éœ€è¦hexo new page support
  # ...

post:
  footer: ğŸŒŠçœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”ğŸŒŠ
  themeInfo: true # æ˜¯å¦å¼€å¯åº•éƒ¨å³ä¾§å£°æ˜æœ¬ç«™ä¿¡æ¯
  width: middle  #  middle | big
  titlePosition: center # left ï½œ center æ–‡ç« æ ‡é¢˜çš„ä½ç½®

# ç›¸å¯¹äºsourceç›®å½•ä¸‹çš„å¤´åƒurl
favicon: /img/favicon.webp # é»˜è®¤æ–¹å½¢å¤´åƒ
isRoundedAvatar: false # æ˜¯å¦åœ†å½¢å¤´åƒ
isAvatarRotating: false # åœ†å½¢å¤´åƒæ˜¯å¦å¼€å¯æ‚¬æµ®æ—‹è½¬

# æ˜¯å¦å¯ç”¨ä¸€äº›ç‰¹è‰²å·¥å…· false | true
tool:
  darkMode: true # æš—é»‘æ¨¡å¼
  returnToTop: true # å›åˆ°é¡¶éƒ¨æŒ‰é’®
  returnToLast: true # å›é€€é¡µé¢æŒ‰é’®
  topToc: true # æ–‡ç« é¡¶éƒ¨ç›®å½•
  leftToc: true # æ–‡ç« å·¦ä¾§ç›®å½• ç›®å‰ä»…æ”¯æŒå¤§å±å¹•æµ®ç°
  recentUpdatePost: false # listé¡µé¢å°†ä¼šæ–°å¢ä¸€ä¸ªâ€œæœ€è¿‘æ›´æ–°â€æ¨¡å—ï¼Œå±•ç¤ºæœ€è¿‘3ç¯‡æ–‡ç« ï¼Œæœ€è¿‘æ›´æ–°å¯ç‚¹å‡»è·³è½¬è‡³ "æœ€è¿‘æ›´æ–°åˆ—è¡¨é¡µé¢"
  # A4å¯åŠ¨å°†ä¼šè‡ªåŠ¨åˆ›å»ºâ€œæœ€è¿‘æ›´æ–°é¡µé¢â€ï¼šurlä¸º /recent-updates è¯·è‡ªè¡Œä½¿ç”¨
  # å¦‚æœä½ å‘ç°ä½ çš„æœ€è¿‘æ›´æ–°æ—¶é—´æ€»æ˜¯å½“å¤©éƒ¨ç½²çš„æ—¶é—´ï¼Œè¯·çœ‹ https://ninojay.top/2023/writeByGithub-2/#2024.09.26æ›´æ–°è¯´æ˜


# ---------------------------------------------------------------------------------------
# ä»¥ä¸Šä¸ºåŸºæœ¬é…ç½®ï¼Œå®ç°äº†A4ä¸»é¢˜è¿½æ±‚çš„çº¯å‡€é£
#
# ä»¥ä¸‹ä¸º éå¿…è¦ä¸å¿…æ›´æ”¹çš„é…ç½®
#
# psï¼šè¿˜æœ‰ç»è¿‡A4ä½œè€…æµ‹è¯•ï¼Œå¯ä¾›ä½ ä½¿ç”¨çš„æ’ä»¶ï¼Œè¯¦è§ï¼šhttps://ninojay.top/tags/hexoPlugin/
# ---------------------------------------------------------------------------------------

# é¦–é¡µé¡µé¢çš„å…¶ä»–é…ç½®
indexInfo:
  allWordCount: true # æ˜¯å¦æ˜¾ç¤ºå…¨ç«™å­—æ•°ç»Ÿè®¡
  allViewCount: true # æ˜¯å¦æ˜¾ç¤ºå…¨ç«™è®¿é—®é‡ç»Ÿè®¡

# æ–‡ç« é¡µé¢çš„ä¿¡æ¯
postInfo:
  updateDate: true # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€è¿‘æ›´æ–°æ—¶é—´
  wordCount: true # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« å­—æ•°ç»Ÿè®¡
  readTime: true # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« é¢„è®¡é˜…è¯»è€—æ—¶
  viewCount: true # é˜…è¯»é‡ç»Ÿè®¡
  prevAndNextLink: # é“¾æ¥ï¼šä¸Šä¸€ç¯‡å’Œä¸‹ä¸€ç¯‡æ–‡ç« 
    status: true # true | false # è®¾ç½®ä¸ºtrue,ä¸‹é¢ä¸¤é¡¹æ‰ä¼šç”Ÿæ•ˆ
    prevInfo: ä¸Šä¸€ç¯‡ # ä¸Šä¸€ç¯‡æç¤ºæ–‡æ¡ˆï¼Œç…§é¡¾åˆ°è‹±æ–‡ç”¨æˆ·ï¼Œä½ å¯ä»¥è®¾ç½®ä¸ºè‹±è¯­å•è¯
    nextInfo: ä¸‹ä¸€ç¯‡ # ä¸‹ä¸€ç¯‡æç¤ºæ–‡æ¡ˆï¼Œç…§é¡¾åˆ°è‹±æ–‡ç”¨æˆ·ï¼Œä½ å¯ä»¥è®¾ç½®ä¸ºè‹±è¯­å•è¯
  endContent: ä»¥ä¸Š # å½“ä½ ä½¿ç”¨äº† è¯„è®ºåŠŸèƒ½ï¼Œæ­¤é…ç½®æ‰ä¼šç”Ÿæ•ˆ

# åˆ—è¡¨é¡µé¢çš„é…ç½®
listInfo:
  enable: false
  hoverStyle: underline # box | circle | underline | highlight | strike-through | crossed-off # é¼ æ ‡æ‚¬æµ®åœ¨æ–‡ç« åˆ—è¡¨ä¸Šæ—¶çš„æ ·å¼
  hoverColor: "#4f7dde" # é¼ æ ‡æ‚¬æµ®åœ¨æ–‡ç« åˆ—è¡¨ä¸Šæ—¶çš„é¢œè‰²
  animationDuration: 800 # é¼ æ ‡æ‚¬æµ®åœ¨æ–‡ç« åˆ—è¡¨ä¸Šæ—¶çš„åŠ¨ç”»æ—¶é•¿,å•ä½msæ¯«ç§’

# ä½ å¯èƒ½ä¼šç”¨åˆ°çš„ https://ninojay.top/2023/website-cdn/
cdn:
  enable: false # å¦‚æœä½ ä¿®æ”¹äº† css/js ï¼Œä¹Ÿè®¸éœ€è¦æŠŠcdnè®¾ç½®ä¸ºfalseæ‰ä¼šç”Ÿæ•ˆ
  choose: zzko  # zzko | aliyun | unpkg| jsdelivr  # éƒ½è°ƒæ•´ä¸ºåˆ©äºå›½å†…çš„cdnï¼Œå»ºè®®ä½¿ç”¨é»˜è®¤çš„ zzko å³å¯
  # å› ä¸ºæ˜¯å…è´¹CDNï¼Œæ‰€ä»¥æœ‰æŒ‚çš„é£é™©ï¼Œä¸€æ—¦å‘ç°ç½‘ç«™æ ·å¼å‡ºç°åŸæ¥æ²¡æœ‰çš„é—®é¢˜ï¼Œè¯·å°è¯•å…³é—­CDN

# å®éªŒæ€§åŠŸèƒ½ï¼šA4è‰²è°ƒè°ƒæ•´ï¼šé¢œè‰²æ­é…æ˜¯å¾ˆä¸»è§‚çš„è¡Œä¸º
# è®¾ç½®ä¸º false ä¸º A4 é»˜è®¤ç°ç™½è‰²è°ƒï¼Œå¯è®¾ç½®ä¸º true ç›´æ¥å¯åŠ¨ ä½“éªŒä¸‹ å¦ä¸€ç§æŠ¤çœ¼é¢„ç½®è‰²è°ƒ
# æ³¨ï¼šé¢œè‰²ä»£ç éœ€åŠ â€œ#â€ï¼Œé¢œè‰²å•è¯ä¸éœ€è¦åŠ â€œ#â€
# æ›´å¤šA4è‰²è°ƒæ­é…æ¨èï¼šhttps://ninojay.top/hexoplugin/A4-color-change/
color:
  enable: false # true | false
  font: "#9e5345" # å­—ä½“é¢œè‰²
  background: "#e8e0c9" # æœ€åº•éƒ¨å±‚èƒŒæ™¯é¢œè‰²
  indexBackGround: "#efeae2" # é¦–é¡µå±‚é¢œè‰²
  postBackGround: "#efeae2" # æ–‡ç« é¡µå±‚é¢œè‰²
  codeBackGround: "#e8e0c9" # ä»£ç å—èƒŒæ™¯é¢œè‰²
  codeFont: "#2e5041" # ä»£ç å—å­—ä½“é¢œè‰²
  linkBeforeClick: "#2e5041" # é“¾æ¥ç‚¹å‡»å‰çš„é¢œè‰²
  linkAfterClick: "#9c9caf" # é“¾æ¥ç‚¹å‡»åçš„é¢œè‰²

# A4èƒŒæ™¯å¼•å…¥å›¾ç‰‡
# å›¾ç‰‡ä½ åº”è¯¥å…ˆæ”¾åˆ° sourceä¸‹ï¼Œä¸‹é¢é€‰é¡¹çš„å›¾ç‰‡è·¯å¾„ å³ä¸º ç›¸å¯¹äº source ç›®å½•çš„è·¯å¾„
imageShow:
  enable: false
  background: /img/favicon.webp # æœ€åº•éƒ¨å±‚èƒŒæ™¯

# A4é»˜è®¤ä¸­æ–‡ä½¿ç”¨éœé¹œæ–‡æ¥·ï¼Œå¦‚æœä½ æƒ³å…³é—­è¿™ç§å­—ä½“ï¼Œé¦–å…ˆä¿è¯enableä¸º true æ¥ç€å¯ä»¥å¼€å…³å¯¹åº”å­—ä½“
font:
  enable: false # æ˜¯å¦ä½¿ç”¨å­—ä½“å¼€å…³åŠŸèƒ½
  LXGWWenKai: true # éœé¹œæ–‡æ¥· å¦‚æœå…³é—­ï¼Œä¸­æ–‡åˆ™ä½¿ç”¨çš„æ˜¯ æ€æºå®‹ä½“ï¼Œæ€æºå®‹ä½“ä¸æä¾›å…³é—­

# å›¾ç‰‡å¹»ç¯ç‰‡é…ç½®
lightgallery:
  thumbnail: true # æ˜¾ç¤ºç¼©ç•¥å›¾
  zoom: true # å¯ç”¨ç¼©æ”¾åŠŸèƒ½
  rotate: true # å¯ç”¨æ—‹è½¬åŠŸèƒ½èƒ½
  autoplay: true # å¯ç”¨è‡ªåŠ¨æ’­æ”¾åŠŸèƒ½
  fullScreen: true # å¯ç”¨å…¨å±åŠŸèƒ½
  pager: false # é¡µç 

# ---------------------------------------------------------------------------------------
# Comment plugin
# è¯„è®ºæ’ä»¶ï¼šéœ€è¦æ ¹æ®æ•™ç¨‹è‡ªè¡Œéƒ¨ç½²è¯„è®ºæœåŠ¡
# ---------------------------------------------------------------------------------------
comment:
  enable: false
  use: waline # values: walineã€twikooã€giscusã€artalk

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:  # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html
    placeholder: ç•™ä¸‹ä½ çš„è¯„è®ºå§ã€‚ # è¯„è®ºæ¡†èƒŒæ™¯ä¿¡æ¯

  # Twikoo
  # See: https://twikoo.js.org/quick-start.html
  twikoo:
    envId:  # è…¾è®¯äº‘ç¯å¢ƒå¡« envIdï¼›å…¶å®ƒç¯å¢ƒå¡«åœ°å€
    region:  # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œè…¾è®¯äº‘ç¯å¢ƒå¡« ap-shanghai æˆ– ap-guangzhouï¼›å…¶å®ƒç¯å¢ƒä¸å¡«
    lang:  # ç”¨äºæ‰‹åŠ¨è®¾å®šè¯„è®ºåŒºè¯­è¨€ï¼Œæ”¯æŒçš„è¯­è¨€åˆ—è¡¨ https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js

  # Giscus
  # See: https://giscus.app
  giscus:
    dataRepo: # data-repoï¼Œå¿…å¡«
    dataRepoId: # data-repo-idï¼Œå¿…å¡«
    dataCategory: # data-categoryï¼Œé€‰å¡«
    dataCategoryId: # data-category-idï¼Œdata-mapping="number"æ—¶ä¸å¡«ï¼Œå…¶ä»–æƒ…å†µä¸‹å¿…å¡«
    dataMapping: pathname # data-mapping
    dataTerm: # data-termï¼Œdata-mapping="number"æˆ–"specific"æ—¶å¿…å¡«ï¼Œå…¶ä»–æƒ…å†µä¸‹ä¸å¡«
    dataStrict: "0" # data-strict
    dataReactionsEnabled: "1" # data-reactions-enabled
    dataEmitMetadata: "0" # data-emit-metadata
    dataInputPosition: bottom # data-input-position
    dataTheme: preferred_color_scheme # data-theme
    dataLang: zh-CN # data-lang
    dataLoading: # data-loadingï¼Œé€‰å¡«
    crossorigin: anonymous # crossorigin
    async: true # async

  # Artalk
  # See: https://artalk.js.org/guide/deploy.html
  artalk:
    server:  # Artalk åç«¯åœ°å€

inject:
  css: css/custom.css # æ‰¾åˆ°è¯¥æ–‡ä»¶åï¼Œç¼–å†™ä½ çš„cssæ ·å¼ï¼Œæ¯ä¸ªé¡µé¢éƒ½ä¼šè‡ªåŠ¨å¼•å…¥

version: v1.9.8
