menu:
  é¦–é¡µ: /  #éœ€è¦hexo new page index,åœ¨index/index.mdå¡«å†™çš„å†…å®¹å°†ä¼šå±•ç°åœ¨é¦–é¡µä¸Š
  æ–‡ç« : /list/ # éœ€è¦hexo new page list
  # æ·»åŠ å…¶ä»–é¡µé¢æ ¼å¼ä¸¾ä¾‹ï¼š
  # å…³äº: /about/ # éœ€è¦hexo new page about
  # æ ‡ç­¾: /tags/ #éœ€è¦hexo new page tags
  # åˆ†ç±»: /categories/ # éœ€è¦hexo new page categories

footerLink: # åº•éƒ¨çš„é“¾æ¥è‡ªå®šä¹‰
  info: Â© 1949-2023 china  # infoè¿™ä¸ªå•è¯ä¸èƒ½ä¿®æ”¹ï¼Œä¸æƒ³ä½¿ç”¨å¯ä¸ºç©º
  # æ·»åŠ é“¾æ¥æ ¼å¼ä¸¾ä¾‹
  # å‹é“¾: /friends/
  # è”ç³»: /contact/
  # æ”¯æŒ: /support/

index:  # é¦–é¡µçš„é¡µçœ‰é¡µè„š
  header: çœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜” 
  footer: Email:123456789@gmail.com # é™¤äº†å¯ä»¥å¡«å†™ä»»ä½•æ–‡å­—å¤–ï¼Œå¯ä»¥è‡ªåŠ¨é‚®ç®±é“¾æ¥åŒ–ï¼Œä½†éœ€æŒ‰ç…§è¿™ä¸ªæ ¼å¼å¡«å†™ï¼šEmail:xxx@gmail.com

post: #é™¤é¦–é¡µä¹‹å¤–é¡µé¢çš„é¡µè„š 
  footer: ğŸŒŠçœ‹è¿‡å¤§æµ·çš„äººä¸ä¼šå¿˜è®°æµ·çš„å¹¿é˜”ğŸŒŠ 


# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: false 
  use: waline # values: waline

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:   # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html

cdn:
  enable: true

version: v1.6.2
